### ISSUE TITLE
review

### ISSUE THREAD

**Issue by ShimiSun** [taysea/photo-search-app#4]
Overall looks great 💟  good usage of styled-components, hooks, routing, and grommet.
I think you've gained a lot of mileage of front-end development with this app, I'm happy you were able to own and execute it! 
See my review comments below, nothing too big but embracing them will help grow your mindset for future projects, most of them are food for thought...

1. Have you tried using https://codesandbox.io/s/4jltk instead of  https://github.com/taysea/photo-search-app/blob/a0202abd8b37d0b8cae5b73b29370f56daafb565/package.json#L15
we are encouraged to use as less external packages as possible, and leverage grommet as much possible.

1. Using CRA can add a lot of dependencies you don't need, for a cleaner usage on future projects try to use https://github.com/ShimiSun/grommet-template-prettier, or use your own webpack boilerplate that is tidy and clean.

1. Learn a little bit about prettier, I see you are using `.prettierignore`, but I don't see how you are actually using `prettier`, so take a look if this file can be removed if it is not being used (less is better). Prettier will help you build consistently semantic apps. https://prettier.io/ (BTW, at JSConf some people commented it looks like the HPEDev logo :) )

1. Why do you use `yarn` if you are not using it https://github.com/taysea/photo-search-app/blob/a0202abd8b37d0b8cae5b73b29370f56daafb565/package.json#L50?
I also see you have a `yarn.lock` file while you are not really using yarn (according to your readme), this may be confusing for dependency management.

1. The project Readme file should explain a little more what this project is trying to solve, or which features it offers, I would put more details into it, people like to know what are they getting themselves into and some context will create a positive experience.

1. Your home page code, App.js, looks great, thanks for refactoring it.

1. I'd encourage to use hooks for ResponsiveContext  https://github.com/taysea/photo-search-app/blob/a0202abd8b37d0b8cae5b73b29370f56daafb565/src/components/Guideline.js#L8 and https://github.com/taysea/photo-search-app/blob/a0202abd8b37d0b8cae5b73b29370f56daafb565/src/components/Palette.js#L56
See my example: 
https://github.com/grommet/grommet/pull/3276

1.  Why not using grommet Paragraph? https://github.com/taysea/photo-search-app/blob/a0202abd8b37d0b8cae5b73b29370f56daafb565/src/components/ProfileInformation.js#L37

1. I think this box is redundant https://github.com/taysea/photo-search-app/blob/a0202abd8b37d0b8cae5b73b29370f56daafb565/src/components/Footer.js#L14

As mentioned ⬆️ , looks great! great work

**Comment by taysea** [comment]
@ShimiSun I made some adjustments based on your review.
- I actually am using the spinner you have in the link. Initially, I used the external spinner but then changed it and just forgot to remove the package. Fixed now!
- I am using yarn, so I added it to the README for clarity and also adjusted the README to explain the project a bit more.
- The prettier logo does look like the HPE Dev one, interesting
- I altered the files with ResponsiveContext so it utilized useContext
- ProfileInformation.js was an old file that isn't actually part of the project anymore. I removed it as well as other unused files.
- You're right. The box was redundant and has been removed.
